DoAnGiuaKyWeb/DoAnGiuaKyWeb/Areas/Admin/Controllers/LoaiSanPhamAdminController.cs
using DoAnGiuaKyWeb.Areas.Admin.Models.BusAdmin;
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnGiuaKyWeb.Areas.Admin.Controllers
{
    public class LoaiSanPhamAdminController : Controller
    {
        // GET: Admin/LoaiSanPhamAdmin
        public ActionResult Index()
        {
            return View(LoaiSanPhamAdmin.DS());
        }

        // GET: Admin/LoaiSanPhamAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSanPhamAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPhamAdmin/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham l)
        {
            try
            {
                // TODO: Add insert logic here
                l.TinhTrang = 0;
                LoaiSanPhamAdmin.Them(l);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPhamAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            return View(LoaiSanPhamAdmin.Update(id));
        }

        // POST: Admin/LoaiSanPhamAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, LoaiSanPham lsp)
        {
            try
            {
                // TODO: Add update logic here
                lsp.Maloaisanpham = null;
                lsp.TinhTrang = 0;
                LoaiSanPhamAdmin.UpdateDS(lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPhamAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/LoaiSanPhamAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult xoatam(string id)
        {
            
                // TODO: Add delete logic here
                LoaiSanPhamAdmin.DeleteDS(id);
                return RedirectToAction("Index");
        }
        public ActionResult KhoiPhucTinhTrang(string id)
        {

            // TODO: Add delete logic here
            LoaiSanPhamAdmin.KhoiPhuc(id);
            return RedirectToAction("Index");
        }
    }
}

DoAnGiuaKyWeb/DoAnGiuaKyWeb/Areas/Admin/Controllers/NhaSanXuatAdminController.cs
using DoAnGiuaKyWeb.Areas.Admin.Models.BusAdmin;
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnGiuaKyWeb.Areas.Admin.Controllers
{
    public class NhaSanXuatAdminController : Controller
    {
        // GET: Admin/NhaSanXuatAdmin
        public ActionResult Index()
        {
            return View(NhaSanXuatAdmin.DS());
        }

        // GET: Admin/NhaSanXuatAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/NhaSanXuatAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhaSanXuatAdmin/Create
        [HttpPost]
        public ActionResult Create(NhaSanXuat collection)
        {
            try
            {
                // TODO: Add insert logic here
                collection.TinhTrang = 0;
                NhaSanXuatAdmin.Them(collection);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/NhaSanXuatAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            return View(NhaSanXuatAdmin.Update(id));
        }

        // POST: Admin/NhaSanXuatAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, NhaSanXuat sx)
        {
            try
            {
                // TODO: Add update logic here
                sx.TinhTrang = 0;
                NhaSanXuatAdmin.UpdateDS(sx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/NhaSanXuatAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/NhaSanXuatAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult xoatam(string id)
        {

            // TODO: Add delete logic here
            NhaSanXuatAdmin.DeleteDS(id);
            return RedirectToAction("Index");
        }
        public ActionResult KhoiPhucTinhTrang(string id)
        {

            // TODO: Add delete logic here
            NhaSanXuatAdmin.KhoiPhuc(id);
            return RedirectToAction("Index");
        }
    }
}

DoAnGiuaKyWeb/DoAnGiuaKyWeb/Areas/Admin/Controllers/SanPhamAdminController.cs
using DoAnGiuaKyWeb.Areas.Admin.Models.BusAdmin;
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnGiuaKyWeb.Areas.Admin.Controllers
{
    public class SanPhamAdminController : Controller
    {
        // GET: Admin/SanPhamAdmin
        public ActionResult Index()
        {
            return View(SanPhamAdmin.DS());
        }

        // GET: Admin/SanPhamAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/SanPhamAdmin/Create
        public ActionResult Create()
        {
            ViewBag.Maloaisanpham = new SelectList(SanPhamAdmin.LoaiSanPham(), "Maloaisanpham", "Tenloaisanpham");
            ViewBag.Manhasanxuat = new SelectList(SanPhamAdmin.NhaSanXuat(), "Manhasanxuat", "Tennhasanxuat");
            return View();
        }

        // POST: Admin/SanPhamAdmin/Create
        [HttpPost,ValidateInput(false)]
        public ActionResult Create(SanPham sp)
        {
            try
            {
                if (HttpContext.Request.Files.Count > 0)
                {
                    var hpf = HttpContext.Request.Files[0];
                    if (hpf.ContentLength > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        string fullPathWithFileName = "/asset/images/" + fileName + ".jpg";
                        hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                        sp.Hinhchinh = fullPathWithFileName;
                    }
                }
                // TODO: Add insert logic here
                sp.Luotview = 0;
                sp.Tinhtrang = "0";
                SanPhamAdmin.Them(sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/SanPhamAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/SanPhamAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/SanPhamAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/SanPhamAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {

            // TODO: Add delete logic here

            SanPhamAdmin.XoaSanPham(id);
            return RedirectToAction("Index");

        }

        public ActionResult xoatam(string id)
        {

            // TODO: Add delete logic here
            SanPhamAdmin.DeleteDS(id);
            return RedirectToAction("Index");
        }
        public ActionResult KhoiPhucTinhTrang(string id)
        {

            // TODO: Add delete logic here
            SanPhamAdmin.KhoiPhuc(id);
            return RedirectToAction("Index");
        }
    }
}

DoAnGiuaKyWeb/DoAnGiuaKyWeb/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Areas/asste/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/Areas/asste/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Plugin CSS -->
    <link href="~/Areas/asste/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Areas/asste/css/sb-admin.css" rel="stylesheet">
    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.js"></script>
    <script>
        tinymce.init({
            selector: '.tinymce',
            height: 500,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
            ],
            toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
            image_advtab: true,
        });
    </script>
</head>
<body>
    <!-- Navigation -->
    <nav id="mainNav" class="navbar static-top navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <div class="collapse navbar-collapse" id="navbarExample">
            <ul class="sidebar-nav navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Ixdex","SanPhamAdmin")"><i class="fa fa-fw fa-dashboard"></i>Quản Lý Sản Phẩm</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Ixdex","NhaSanXuatAdmin")"><i class="fa fa-fw fa-area-chart"></i> Quản Lý Nhà Sản Xuất</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Ixdex","LoaiSanPhamAdmin")"><i class="fa fa-fw fa-table"></i>Quản Lý Loại Sản Phẩm</a>
                </li>
               
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" href="#" id="messagesDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-envelope"></i> <span class="hidden-lg-up">Messages <span class="badge badge-pill badge-primary">12 New</span></span>
                        <span class="new-indicator text-primary hidden-md-down"><i class="fa fa-fw fa-circle"></i><span class="number">12</span></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                        <h6 class="dropdown-header">New Messages:</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>David Miller</strong> <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>Jane Smith</strong> <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>John Doe</strong> <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item small" href="#">
                            View all messages
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" href="#" id="alertsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-bell"></i> <span class="hidden-lg-up">Alerts <span class="badge badge-pill badge-warning">6 New</span></span>
                        <span class="new-indicator text-warning hidden-md-down"><i class="fa fa-fw fa-circle"></i><span class="number">6</span></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0 mr-lg-2">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa fa-fw fa-sign-out"></i> Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content-wrapper py-3">
        @RenderBody()
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <a class="scroll-to-top rounded" href="#">
        <i class="fa fa-chevron-up"></i>
    </a>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Areas/asste/vendor/jquery/jquery.min.js"></script>
    <script src="~/Areas/asste/vendor/tether/tether.min.js"></script>
    <script src="~/Areas/asste/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/Areas/asste/vendor/chart.js/Chart.min.js"></script>
    <script src="~/Areas/asste/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Areas/asste/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Areas/asste/js/sb-admin.min.js"></script>
</body>
</html>